---
title: "MICB425 Portfolio - Microbial Ecological Genomics: From Genomes to Biomes, Spring 2018"
author: "Student First Name, Preferred Name, Last Name, Student ID"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
---
# Module 01
Reserve the first level headings (#) for the start of a new Module. This will help to organize your portfolio in an intuitive fashion.  
**Note: Please edit this template to your heart's content. This is meant to be the armature upon which you build your individual portfolio. You do not need to keep this instructive text in your final portfolio, although you do need to keep module and assignment names so we can identify what is what.**


## Module 01 portfolio check
The first of your second level headers (##) is to be used for the portfolio content checks. The Module 01 portfolio check has been built for you directly into this template, but will also be available as a stand-alone markdown document available on the MICB425 GitHub so that you know what is required in each module section in your portfolio. The completion status and comments will be filled in by the instructors during portfolio checks when your current portfolios are pulled from GitHub.

* Installation check
    + Completion status:
    + Comments:
* Portfolio repo setup
    + Completion status: 
    + Comments:
* RMarkdown Pretty PDF Challenge
    + Completion status:
    + Comments:
* Evidence worksheet_01
    + Completion status:
    + Comments:
* Evidence worksheet_02
    + Completion status:
    + Comments:
* Evidence worksheet_03
    + Completion status:
    + Comments:
* Problem Set_01
    + Completion status:
    + Comments:
* Problem Set_02
    + Completion status:
    + Comments:
* Writing assessment_01
    + Completion status:
    + Comments:
* Additional Readings
    + Completion status:
    + Comments  
    
## Data science Friday  
The remaining second level headers (##) are for separating data science Friday, regular course, and project content. In this module, you will only need to include data science Friday and regular course content; projects will come later in the course.

### Installation check
Third level headers (###) should be used for links to assignments, evidence worksheets, problem sets, and readings, as seen here.  

Use this space to include your installation screenshots.



### Portfolio repo setup
Detail the code you used to create, initialize, and push your portfolio repo to GitHub. This will be helpful as you will need to repeat many of these steps to update your porfolio throughout the course.



### RMarkdown pretty PDF challenge
Paste your code from the in-class activity of recreating the example PDF.
      - Separate file (See Assignment_3.Rmd)


## Origins and Earth Systems
### Evidence worksheet 01 
The template for the first Evidence Worksheet has been included here. The first thing for any assignment should link(s) to any relevant literature (which should be included as full citations in a module references section below).

You can copy-paste in the answers you recorded when working through the evidence worksheet into this portfolio template. 

As you include Evidence worksheets and Problem sets in the future, ensure that you delineate Questions/Learning Objectives/etc. by using headers that are 4th level and greater. This will still create header markings when you render (knit) the document, but will exclude these levels from the Table of Contents. That's a good thing. You don't' want to clutter the Table of Contents too much.

[Whitman *et al* 1998](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33863/)

#### Learning objectives
Describe the numerical abundance of microbial life in relation to ecology and biogeochemistry of Earth systems. 

#### General questions
* What were the main questions being asked?  
      - what is the number of prokaryotes on Earth  
      - What is the range of prokaryotes present in specific parts of the Earth  
(none of these questions were directly stated in the paper)

* What were the primary methodological approaches used?  
      - No methods were described in the paper  
      - Literature search/survey was done in order to obtain numbers for making estimates of the environments  
      - Number calculated (of hypothetical sample) was extrapolated to estimate the number of prokaryotes present  


* Summarize the main results or findings.  
      - Cellular production rate is the highest in the open ocean  
      - Prokaryotes contribute to approx. 60-100% of the total C found in plants (make up big portion of total C on Earth)  
      - Subsurface = major habitat for prokaryotes (greatest in terms of number of prokaryotes present than that found in other parts of the biosphere)  
      - Data not completely accurate since mostly estimated by extrapolation (may need to be revised)  
      - Turnover time is fastest in domestic mammals (rapidly growing population, although it's the least in terms of population size)  
      - Cellular productivity of subsurface prokaryotes comparable to that of domestic animals  


* Do new questions arise from the results?  
      - Yes. The paper estimated the number of prokaryotes. How does the number of bacteria compare to that of archaea?  
      - How does climate change affect prokaryote abundance? (Paper was published in 1998; if done again today, what would the results be and how would they compare?)  

* Were there any specific challenges or advantages in understanding the paper (*e.g.* did the authors provide sufficient background information to understand experimental logic, were methods explained adequately, were any specific assumptions made, were conclusions justified based on the evidence, were the figures or tables useful and easy to understand)?  
      - Not much background information nor description of methods were discussed in the paper  
      - Did literature survey so each method will possibly have diferences (variability of results), as well as different uncertainties (error rate). Data will vary across reported results.  
      - Didn't really state purpose of the paper, particularly in the abstract; can make purpose more explicit so that it is easier to tie it to the bigger picture and help the reader understand the importance of the study  


### Problem set 01
#### Learning objectives: 
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.

#### Specific questions:
* What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.   


      - Aquatic: 1.181 x 10^30^ cells  
        - Freshwater - 1.31 x 10^26^ cells  
        - Saline lakes - 1.0 x 10^26^ cells  
        - Marine - 1.18 x 10^29^ cells
      - Soil: 2.56 x 10^29^ cells  
      - Subsurface: 3.8 x 10^30^ cells  
        - 10 cm marine  
        - 8 m terrestrial  


* What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?  

      - cell density: 5 x 10^5^ cells/mL  
      - Prochlorococcus spp. -> cell density: 4 x 10^4^ cells/mL  
      - fraction = (4 x 10^4^ cells/mL) / (5 x 10^5^ cells/mL) = 0.08 = 8 % marine cyanobacteria
      - Significant portion of upper oceanic microbes are photosynthetic cyanobacteria needed to fix carbon -> provides C for everyone = high turnover rate  
      

* What is the difference between an autotroph, heterotroph, and a lithotroph based on information provided in the text?  

 Autotroph: "Self-nourishing"
             Fix inorganic carbon (CO2)  
 Heterotroph: assimilate organic carbon  
 Lithotroph: use inorganic substrates (carbon) for energy source    

* Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?  

      - Deep habitats supporting life:  
      - Subsurface: Terrestrial = 4 km from sediment (a bit below Mariana's Trench)  
      - Temperature is limiting factor (approx. 125 degrees Celsius); change in temp. is approx. 22 degrees Celsius per km depth.  


* Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?  

      - 57-77 km above Earth's surface (a bit above Mt. Everest)  
      - Limiting factor is radiation  

* Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth’s biosphere measured in km?  

      - 61-81 km = range of Earth's biosphere

* How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)  

      - (Population) x (Turnover/yr) = Cells/yr  
      - Marine Heterotrophs:  
        - (3.6 x 10^28^ cells x 365 days) / 16 turnovers = 8.2 x 10^29^  


* What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?  

      - C content = amount of organic C stored
      - C assimilation efficiency = inorganic C -> organic C
      - Turnover rate = fraction of C that leaves a reservoir per specified time
      - Carbon efficiency = 20%  
        - 5-20 fg C per Cell = 20 x 10^-30^ Pg/cell  
        - (3.6 x 10^28^ cells) x (20 x 10^-30^ Pg/cell) = 0.72 Pg C in marine
        - Heterotrophs:  
          - 4 x 0.72 = 2.88 Pg/yr  
      - (C consumed) / (turnover rate)
      - more sunlight near surface
      - high nutrient = high energy = high turnover rate  

* How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10^-7^ per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)
     - [( (4 x 10^-7^ mutation rate per gene) /cell)^4^ x ( (3.6 x 10^28^ cells) /16 days) x (1 day/24 hrs)]^-1^ = 0.42 hrs for 4 mutations    
     
     
* Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt?
     - Point mutations are not the only way. Horizontal and lateral gene transfer can also occur. Conjugation by plasmid, transduction by virus, and transformation by naked virus can all occur. High genetic diversity and adaptive potential may possibly lead to new species.    
     
     
* What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text? 
    - Upper 200 m of marine habitat has higher genetic diversity than in domestic animals. 
    - Open ocean prokaryotes have much greater adaptive potential than those in soil, subsurface and domestic animals. 
    - Greater prokaryotic abundance in unconsolidated subsurface than in soil.


### Module 01 references
Utilize this space to include a bibliography of any literature you want associated with this module. We recommend keeping this as the final header under each module.

An example for Whitman and Wiebe (1998) has been included below.

Whitman WB, Coleman DC, and Wiebe WJ. 1998. Prokaryotes: The unseen majority. Proc Natl Acad Sci USA. 95(12):6578–6583.  [PMC33863](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33863/)

