---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing
Fixed errors (capitalization, R-formatting) in abstract based on feedback.

## Introduction
### Literature research  

Did literature research to write all of introduction.  

### Writing  
Wrote all of introduction.  

### Editing  
Edited introduction based on feedback. Fixed R-formatting errors.  

## Methods
### Writing

### Editing
Fixed R-formatting and added/edited sentences based on feedback.

## Results
### Analysis 

### Figures

### Writing

### Editing
Fixed R-formatting and added/edited sentences based on feedback. Troubleshooting; found some syntax errors which caused a figure to show up incorrectly. Moved figure codes to relevant locations so it would be easier to refer (and mark) to when mentioned in text.

## Discussion
### Literature research  

Found and read papers relevant to cyanobacteria. Formatted all references.  

### Writing  

Wrote about future directions for the project.  

### Editing  

Fixed R-formatting and added/edited sentences based on feedback.
