---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing
Read abstract and edited sentences for better flow.

## Introduction
### Literature research  

Did literature research to write all of introduction.  

### Writing  
Wrote all of introduction.  

### Editing  
Fixed sentences according to feedback from group members.

## Methods
### Writing

### Editing
Fixed R-formatting and added/edited sentences based on feedback.

## Results
### Analysis 

### Figures

### Writing

### Editing
Fixed R-formatting. Edited sentences to reduce redundancy and have smoother transitions between paragraphs.

## Discussion
### Literature research  

Found and read papers relevant to our portion of denitrification (nitrate reductase/*narG*) and nitrogen cycle. Formatted all references.  

### Writing  

Wrote a portion of opening paragraph which frames gene of interest.  

### Editing  

Fixed R-formatting. Edited sentences to reduce redundancy between paragraphs written by different people and made transitions between paragraphs less awkward.
